// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///



class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO3qcfK10r96ZAdVnysFZVK6TxER_kNAc',
    appId: '1:828174504251:web:ae7c3d22e99f0cff5aa71e',
    messagingSenderId: '828174504251',
    projectId: 'chat-5d121',
    authDomain: 'chat-5d121.firebaseapp.com',
    storageBucket: 'chat-5d121.appspot.com',
    measurementId: 'G-PGVE239W7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkyQdfWVz8GLf8Q0Xkq9TQxsd0Tg0QnfE',
    appId: '1:828174504251:android:0ff1fbe97fe260e35aa71e',
    messagingSenderId: '828174504251',
    projectId: 'chat-5d121',
    storageBucket: 'chat-5d121.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuJsZCaiHnAHc1mdlX4AD11dPTASyH_iQ',
    appId: '1:828174504251:ios:1d247b73b68247485aa71e',
    messagingSenderId: '828174504251',
    projectId: 'chat-5d121',
    storageBucket: 'chat-5d121.appspot.com',
    iosClientId: '828174504251-0l0phj3l1hoipcsbtoahpoecff5snp4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuJsZCaiHnAHc1mdlX4AD11dPTASyH_iQ',
    appId: '1:828174504251:ios:1d247b73b68247485aa71e',
    messagingSenderId: '828174504251',
    projectId: 'chat-5d121',
    storageBucket: 'chat-5d121.appspot.com',
    iosClientId: '828174504251-0l0phj3l1hoipcsbtoahpoecff5snp4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
